# Generated by Django 5.1.6 on 2025-03-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="answer",
            field=models.CharField(default="Default Answer", max_length=100),
        ),
    ]
